### ISSUE TITLE
Lorsque la souris n'est plus sur le lecteur vidéo faire disparaitre ou minimiser le curseur

### ISSUE THREAD

**Issue by laurentlp** [TSAP-Laval/acquisition-frontend#100]
### Before submitting an issue, make sure you have:
- [X] Read the [README](https://github.com/TSAP-Laval/acquisition-frontend/blob/master/README.md)
- [X] [Searched](https://github.com/TSAP-Laval/acquisition-frontend/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/TSAP-Laval/acquisition-frontend/tree/master/tests)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

Lorsque l'on joue la vidéo, les contrôles apparaissent pour permettre de manipuler la vidéo, par contre, lorsque l'on quitte la vidéo avec notre souris, le curseur du temps reste à la même position... Il devrait plutôt descendre comme les autres contrôles

**Comment by Alexandrehebertvincent** [comment]
PR #138
