### ISSUE TITLE
Lorsque l'on utilise le contrôle permettant plus de précision, arrêter la vidéo

### ISSUE THREAD

**Issue by laurentlp** [TSAP-Laval/acquisition-frontend#101]
### Before submitting an issue, make sure you have:
- [X] Read the [README](https://github.com/TSAP-Laval/acquisition-frontend/blob/master/README.md)
- [X] [Searched](https://github.com/TSAP-Laval/acquisition-frontend/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/TSAP-Laval/acquisition-frontend/tree/master/tests)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

Lorsque l'on décide de faire une avance plus précise avec le 'slider' de droite, la vidéo ne se pause pas et donc il devient plus difficile d'être précis... Un peu comme le contrôle du temps.

**Comment by Alexandrehebertvincent** [comment]
PR #137
