### ISSUE TITLE
Utilisation de bootstrap react et non bootstrap.js

### ISSUE THREAD

**Issue by laurentlp** [TSAP-Laval/acquisition-frontend#118]
## Before submitting an issue, make sure you have:
- [X] Read the [README](https://github.com/TSAP-Laval/acquisition-frontend/blob/master/README.md)
- [X] [Searched](https://github.com/TSAP-Laval/acquisition-frontend/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/TSAP-Laval/acquisition-frontend/tree/master/tests)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for a new functionality)
- [X] Enhancement
- [ ] Other

---

### Describe your issue

Pour ma partie, j'ai utilisé Bootstrap directement depuis le fichier JS. Logiquement, je devrais utiliser la librairie react à la place...

**Comment by mLaribi** [comment]
:+1:

**Comment by laurentlp** [comment]
@mLaribi Je pense pas que tu utilise beaucoup de bootstrap.js, par contre, JQuery oui ! Je sais pas si tu t'en rends compte, mais de ne pas utiliser flux revient à ne pas utiliser la force du framework et donc tu devrais plutôt focuser sur cette architecture là et enlever toute trace de JQuery!!! https://github.com/TSAP-Laval/acquisition-frontend/issues/122. Une fois que tu auras corrigé cet égard, s'il te plaît, arrange cette issue https://github.com/TSAP-Laval/acquisition-frontend/issues/52 !!!

**Comment by laurentlp** [comment]
Fix https://github.com/TSAP-Laval/acquisition-frontend/pull/174
