### ISSUE TITLE
Repenser la création des infos d'analyse (joueurs, équipes, coachs, saisons, actions, etc)

### ISSUE THREAD

**Issue by laurentlp** [TSAP-Laval/acquisition-frontend#119]
### Before submitting an issue, make sure you have:
- [X] Read the [README](https://github.com/TSAP-Laval/acquisition-frontend/blob/master/README.md)
- [X] [Searched](https://github.com/TSAP-Laval/acquisition-frontend/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/TSAP-Laval/acquisition-frontend/tree/master/tests)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

Pourquoi créer une saison ? Aussi pourquoi devoir entrer la date ? Il ne faudrait pas juste avoir un bouton qui la crée en fonction de la saison actuelle. Je pense que l'on pourrait revoir cette partie ! D'ailleurs, rien ne lie une saison, une équipe, leurs coachs et les joueurs ensemble. Lorsque des informations sont ajoutés, il faudrait préférablement spécifier la saison, être plus ergonomique pour la création (ne pas mettre 6 onglets et devoir changer pour ajouter un joueur ou en créer un à chaque fois...). La logique derrière est bonne, mais, si l'on veut impressionner et faciliter la vie du client, je suis persuadé qu'il faudrait la revoir !

**Comment by mLaribi** [comment]
En ajoutant un coach je vais préciser la saison actuelle lors de la création d'un nouveau coach.

**Comment by laurentlp** [comment]
@mLaribi Ok! Mais ça ca veut dire qu'il va falloir le faire pour les joueurs, les équipes, les actions.... ?
Il faudrait penser avec un plus grand scale et surtout garder en tête que ça doit être le plus simple possible pour le client !

**Comment by mLaribi** [comment]
@laurentlp Yess! mais pour les actions. Je ne pense pas que ca soit utile? À part si la création d'action doit se faire a chaque saison?
