### ISSUE TITLE
 Pouvez-vous de grâce enlever toutes les références à réussite/échec dans la prochaine version.

### ISSUE THREAD

**Issue by laurentlp** [TSAP-Laval/acquisition-frontend#123]
### Before submitting an issue, make sure you have:
- [X] Read the [README](https://github.com/TSAP-Laval/acquisition-frontend/blob/master/README.md)
- [X] [Searched](https://github.com/TSAP-Laval/acquisition-frontend/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/TSAP-Laval/acquisition-frontend/tree/master/tests)

### Purpose of your issue?
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

 Pouvez-vous de grâce enlever toutes les références à réussite/échec dans la prochaine version. Message de JP, à corriger au plus cr**s merci !

**Comment by alexDeschenes** [comment]
je m'en occupe aujourd'hui!
