### ISSUE TITLE
Enregistrer une action 

### ISSUE THREAD

**Issue by alexDeschenes** [TSAP-Laval/acquisition-frontend#126]
Nous devons faire une analyse profonde pour la façon dont on ajoute une action. Il faut regarder toutes les possibilités d'action pour avoir la façon efficace .

**Comment by laurentlp** [comment]
Si tu utilise pas le template de PR, je vais fermer l'issue ! Aussi, soit un peu plus clair, met plus de contexte, comme si on savait pas c'est quoi le projet plz !
