### ISSUE TITLE
Analyse

### ISSUE THREAD

**Issue by alexDeschenes** [TSAP-Laval/acquisition-frontend#127]
### Before submitting an issue, make sure you have:
- [X] Read the [README](https://github.com/TSAP-Laval/acquisition-frontend/blob/master/README.md)
- [X] [Searched](https://github.com/TSAP-Laval/acquisition-frontend/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/TSAP-Laval/acquisition-frontend/tree/master/tests)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [X] Other

---

### Describe your issue
Analyse pour l'ajout d'une action. Il faut prévoire tout les actions pour pouvoir avoir une méthode éfficace.

[Analyse.pdf](https://github.com/TSAP-Laval/acquisition-frontend/files/888588/Analyse.pdf)

**Comment by laurentlp** [comment]
Goo bon début, Fix un peu la description de ta PR, tu peux faire un preview quand tu modifie, comme ca tu va pouvoir voir à quoi ca va ressembler... Aussi ajout des assignees, labels, projects, milestone, etc

**Comment by laurentlp** [comment]
Pourrais tu faire un google doc, comme ça on pourrait y apporter des modification si l'on souhaite ? Sinon good job ! @alexDeschenes

**Comment by laurentlp** [comment]
@alexDeschenes ??

**Comment by laurentlp** [comment]
Trop tard !
