### ISSUE TITLE
Ajouter les raccourcis clavier pour permettre de contrôler la vidéo !

### ISSUE THREAD

**Issue by laurentlp** [TSAP-Laval/acquisition-frontend#141]
### Before submitting an issue, make sure you have:
- [X] Read the [README](https://github.com/TSAP-Laval/acquisition-frontend/blob/master/README.md)
- [X] [Searched](https://github.com/TSAP-Laval/acquisition-frontend/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/TSAP-Laval/acquisition-frontend/tree/master/tests)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Describe your issue

Il serait très intéressant que l'on puisse contrôler la vidéo avec le clavier ! Ainsi, par exemples, on pourrait faire pause et play avec la touche `espace`, avancer avec les flèche, etc....

**Comment by Alexandrehebertvincent** [comment]
Raccourci:
`p` => Play/Pause
`s` => Stop
`r` => Restart
`left arrow` => Backward
`right arrow` => Forward
`a` => Augmenter la vitesse de recherche
`z`=> Diminuer la vitesse de recherche
`l`=> Afficher la loupe

**Comment by Alexandrehebertvincent** [comment]
#162 on his way!

**Comment by Alexandrehebertvincent** [comment]
**Shortkeys à ajouter:**
`t`=> Afficher le terrain
`v`=> Afficher la vidéo
