### ISSUE TITLE
ajouter des racourcis si possible pour la saison d'une action

### ISSUE THREAD

**Issue by alexDeschenes** [TSAP-Laval/acquisition-frontend#142]
### Before submitting an issue, make sure you have:
- [X] Read the [README](https://github.com/TSAP-Laval/acquisition-frontend/blob/master/README.md)
- [X] [Searched](https://github.com/TSAP-Laval/acquisition-frontend/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/TSAP-Laval/acquisition-frontend/tree/master/tests)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [] Feature request (request for a new functionality)
- [ ] Question
- [X ] Other

### Describe your issue

ajouter des racourcis si possible pour la saison d'une action comme par exemple si on veut reset les canvas on pourrait utiliser esapace etc.

**Comment by laurentlp** [comment]
Pas trop clair comme issue et pas sûr que ce soit tant pertinent, mais je vois tout de même vers quoi tu veux en venir. Au pire détailles plus ton problème !

**Comment by laurentlp** [comment]
Aucun `assignees`, `label`, `milestone`, `projects`.... Je te donne jusqu'à dimanche vers la fin de la journée, sinon je ferme ton issue ! @alexDeschenes
