### ISSUE TITLE
Changement d'architecture vers Flux

### ISSUE THREAD

**Issue by laurentlp** [TSAP-Laval/acquisition-frontend#52]
# Pour mieux comprendre l'architecture flux : 
   - Aller voir la série de vidéo React sur Slack
   - Allez comprendre l'architecture pour l'upload (Architecture qui n'est pas au point donc simplement se baser dessus)
   - Liens intéressants : 
        - https://facebook.github.io/flux/
        - https://github.com/facebook/flux (github.com)
        - https://facebook.github.io/flux/docs/overview.html (doc)

- [ ] Alex D
- [x] Alex H
- [x] Laurent
- [ ] Mehdi  _**Regarde mon commentaire et fix tes trucs**_

**Comment by Alexandrehebertvincent** [comment]
It is gonna be so much fun!!! YEA 💯  👯‍♂️

**Comment by Alexandrehebertvincent** [comment]
PR de ma partie #63

**Comment by laurentlp** [comment]
@alexDeschenes ???
@mLaribi ???

**Comment by laurentlp** [comment]
@alexDeschenes ???
@mLaribi ???

**Comment by laurentlp** [comment]
@alexDeschenes ???
@mLaribi ???

**Comment by laurentlp** [comment]
@alexDeschenes ???
@mLaribi ???

C'mon les boys

**Comment by mLaribi** [comment]
@laurentlp Quelque chose que j'oublie?

**Comment by laurentlp** [comment]
@mLaribi T'assurer que ton flux est **parfait**, que t'es indentation sont bonnes, que tu as bien mis des commentaires, utilise aussi un linter pour ton code

**Comment by laurentlp** [comment]
@alexDeschenes ???
@mLaribi ???

**Comment by laurentlp** [comment]
Ca fait 2 mois, de un vous pourriez répondre et de deux, il serait temps que ca se finisse non ?

**Comment by laurentlp** [comment]
@alexDeschenes ???
@mLaribi ???

**Comment by laurentlp** [comment]
@alexDeschenes ???
@mLaribi ???

**Comment by laurentlp** [comment]
ok....
