### ISSUE TITLE
Un administrateur peut éditer un match après avoir chargé le (les) vidéo(s)

### ISSUE THREAD

**Issue by Alexandrehebertvincent** [TSAP-Laval/acquisition-frontend#97]
## Please follow the guide below

- Issues submitted without this template format will likely be **ignored**.
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like.

---

### Before submitting an issue, make sure you have:
- [X] Read the [README](https://github.com/TSAP-Laval/acquisition-frontend/blob/master/README.md)
- [X] [Searched](https://github.com/TSAP-Laval/acquisition-frontend/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] Reviewed the sample code in [tests](https://github.com/TSAP-Laval/acquisition-frontend/tree/master/tests)

### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

- [ ] Lorsqu'un téléchargement est complété, la page d'edit est affiché. **(1 heure)**
- [ ] La partie est passé au component d'edit (VideoPlayer & Edit). **(1 heure)**

**Comment by laurentlp** [comment]
Fait ! https://github.com/TSAP-Laval/acquisition-frontend/pull/149
